apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/mount
  labels:
    testing.upbound.io/example-name: kv-v2
  name: kv-v2
spec:
  deletionPolicy: Delete
  forProvider:
    path: "/testing"
    type: "kv-v2"
  providerConfigRef:
    name: vault-provider-config
